### PR TITLE
test: add support to build with LDC

### PR DESCRIPTION
**Pull request by joakim-brannstrom**
Run Travis-CI with DMD and LDC.

### CODE REVIEW

**Comment by joakim-brannstrom** [comment]
Doesn't work with ldc-0.17-beta2

```bash
ldc2-0.17.0-beta2-linux-x86_64/bin/../import/std/variant.d(2261): Error: cannot implicitly convert expression (variant.peek()) of type const(Tuple!(TypeKind, "type", Typedef!(string, null, "CppVariable"
), "name"))* to Tuple!(TypeKind, "type", Typedef!(string, null, "CppVariable"), "name")*
ldc2-0.17.0-beta2-linux-x86_64/bin/../import/std/variant.d(2261): Error: cannot implicitly convert expression (variant.peek()) of type const(TypeKind)* to TypeKind*
ldc2-0.17.0-beta2-linux-x86_64/bin/../import/std/variant.d(2261): Error: cannot implicitly convert expression (variant.peek()) of type const(Flag)* to Flag*
ldc2-0.17.0-beta2-linux-x86_64/bin/../import/std/variant.d(2012): Error: template instance cpptooling.generator.adapter.generateImpl.genCtor.__lambda4.visitImpl!(true, const(VariantN!(96LU, Tuple!(TypeK
ind, "type", Typedef!(string, null, "CppVariable"), "name"), TypeKind, Flag)), function (Tuple!(TypeKind, "type", Typedef!(string, null, "CppVariable"), "name") tkv) => tkv, function (TypeKind tk) => Tuple(TypeKind(TaggedAlge
braic(, cast(TypeEnum)0), false, false, false, false, false, null), Typedef(null)).this(tk, Typedef(null).this("inst")), delegate (Flag vt) => Tuple(TypeKind(TaggedAlgebraic(, cast(TypeEnum)0), false, false, false, false, fal
se, null), Typedef(null)).this(makeTypeKind("not supported", false, false, false, false, false), Typedef(null).this("not supported"))) error instantiating
source/cpptooling/generator/adapter.d(80):        instantiated from here: visit!(const(VariantN!(96LU, Tuple!(TypeKind, "type", Typedef!(string, null, "CppVariable"), "name"), TypeKind, Flag)))
```

**Comment by joakim-brannstrom** [comment]
Compiles with dmd version 2.069.2+
So should be able to compile deXtool with ldc-0.18.

**Comment by joakim-brannstrom** [comment]
Reduced errors to:

```sh
source/cpptooling/data/symbol/typesymbol.d(46): Error: static assert  "No member in Kind matching parameter CppClass
source/cpptooling/data/symbol/container.d(35):        instantiated from here: TypeSymbol!(CppClass*)
```

**Comment by joakim-brannstrom** [comment]
Ldc 1.0.0 released. Works. Integrated in travis
